### ISSUE TITLE
Viper Edit may disabled microsd in one click

### ISSUE THREAD

**Issue by IMMSPgisgroup** [maks/viper-edit#8]
Viper Edit may disabled microsd in one click without any warning. I saw this on Huawei P Smart Z with last version EMUI 10. This is worked by some "magic" button (red rectangle on picture). 
![image](https://user-images.githubusercontent.com/33963849/85283945-ec410680-b496-11ea-905c-8bda66a39747.png)

**Comment by maks** [comment]
Sorry but I think that part of the interface comes from the Android framework and not ViperEdit, so I'm not sure there is anything I can do to not show that "eject" button next to the sdcard entry.

**Comment by IMMSPgisgroup** [comment]
Yes, I see. I dont very familiar with Android OS, unfortunately :(. I'm sorry to bother you.
